#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 8 ]; then
  echo "usage: $0 OUTPUT VLLM_COMMIT FLASH_ATTN_VERSION TORCH_VERSION BASE_IMAGE PYTHON_VERSION TARGET_PLATFORM TORCH_CUDA_ARCH_LIST" >&2
  exit 2
fi

OUTPUT=$1
VLLM_COMMIT=$2
FLASH_ATTN_VERSION=$3
TORCH_VERSION=$4
BASE_IMAGE=$5
PYTHON_VERSION=$6
TARGET_PLATFORM=$7
TORCH_CUDA_ARCH_LIST=$8

if [[ "$BASE_IMAGE" =~ cuda:([0-9]+)\.([0-9]+)(\.[0-9]+)?- ]]; then
  CUDA_VERSION="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
else
  echo "cannot derive CUDA major.minor from BASE_IMAGE=$BASE_IMAGE" >&2
  exit 2
fi
PYTHON_ABI="cp${PYTHON_VERSION//./}"

printf '%s\n' \
  "VLLM_FORK_COMMIT=${VLLM_COMMIT}" \
  "FLASH_ATTN_VERSION=${FLASH_ATTN_VERSION}" \
  "TORCH_VERSION=${TORCH_VERSION}" \
  "TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}" \
  "CUDA=${CUDA_VERSION} PY=${PYTHON_ABI} PLATFORM=${TARGET_PLATFORM}" \
  > "$OUTPUT"
